spring:
  application:
    name: manager-product-api
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    out-of-order: false
    ignore-migration-patterns: "*:missing"

server:
  port: 8083

logging:
  level:
    com.product: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: INFO

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  packages-to-scan: com.product.controller

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/changeapp_product_dev
    username: changeapp
    password: changeapp123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    create-schemas: true
    schemas: public
    default-schema: public
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    out-of-order: false
    ignore-migration-patterns: "*:missing"

server:
  port: 8083

logging:
  level:
    com.product: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5435/changeapp_product_test
    username: changeapp_product
    password: changeapp_product123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    create-schemas: true
    schemas: public
    default-schema: public
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    out-of-order: false
    ignore-migration-patterns: "*:missing"

server:
  port: 8083

logging:
  level:
    com.product: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN 