spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/changeapp_test
    username: changeapp
    password: changeapp123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

logging:
  level:
    com.exchange: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN 